### ISSUE TITLE
5.1 regression causing cannot represent an object

### ISSUE THREAD

**Issue by ssbarnea** [yaml/pyyaml#297]
I was able to identify a regression caused by changes made in pyyaml 5 which in certain cases can make ansible to choke with somethink looking as:
```
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/__init__.py", line 281, in dump_all
    dumper.represent(data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 29, in represent
    node = self.represent_data(data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 68, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/root/.cache/pre-commit/repoAsFmN9/py_env-python2.7/local/lib/python2.7/site-packages/yaml/representer.py", line 251, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
```

Downgrading pyyaml to versions before 5 does work as a workaround.

**Comment by dchandekstark** [comment]
I'm curious which versions of PyYAML and Ansible @ssbarnea got to work.  With Ansible 2.8.1 and ansible-lint 4.1.0a1.dev27+g69f5e96.d20190628 on Python 3.6.8 I had trouble with PyYAML 4.2b4 also.  PyYAML 3.13 works with my configuration.

**Comment by nitzmahone** [comment]
Can anyone provide a reproduction of the issue?

**Comment by perlpunk** [comment]
I don't know how to reproduce this but we just released 5.2b1 https://pypi.org/project/PyYAML/5.2b1/ which should fix this.

**Comment by perlpunk** [comment]
We released 5.2: https://pypi.org/project/PyYAML/5.2/

**Comment by dchandekstark** [comment]
I still have the issue with PyYAML 5.3, ansible-lint 4.2.0, ansible 2.9.4, Python 3.7.6.  It's not clear to me, however, that this is a PyYAML issue per se, since I only have issues with ansible-lint, not ansible itself.  The stacktraces unfortunately provide only limited help in pinpointing the problem, but I am suspicious of a bug in the linter.  I am still able to use PyYAML 3.13 as a workaround with ansible-lint.

**Comment by ssbarnea** [comment]
More than an year passed since I raised the bug and because I failed to provide a reproducing script now I have no clue how to test it.

If someone can provide a simplified way to reproduce the error we can continue if not... we have no bug.
